[tool.poetry]
name = "rhapsodesproject"
version = "0.1.0"
description = ""
authors = ["Nimira43 <n.rabone72@aol.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
